baseURL = "https://www.yoursite.xyz/"
languageCode = "en-us"

[menu]

  [[menu.main]]
    identifier = "home"
    title = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    title = "About"
    url = "/about/"
    weight = 2

[params]
  name = "My Site"
  tagline = "My Tagline"